name: cos-tool # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Transforms PromQL/LogQL expressions on the fly # 79 char long summary
description: |
  COS Tool is a small Go application used within the Canonical Observability
  Stack for validating and manipulating telemetry and alert rules.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  cos-tool:
    command: cos-tool

architectures:
  - build-on: amd64

parts:
  cos-tool:
    plugin: go
    source: https://github.com/canonical/cos-tool
    source-type: git
    build-snaps:
      - go
    override-build: |
      go build -tags netgo --ldflags '-extldflags "-static"'
      cp $CRAFT_PART_BUILD/cos-tool $CRAFT_PART_INSTALL/
